server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://10.161.12.128:8658/oper_support?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: workflow
    password: ENC(9WkmNwa7sPM0LXQn1MmpKjy5HGr4D9oy)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: pro
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mapper/*.xml
params:
  msgUrl: http://10.161.12.101:8772/skyEyePermission/baseApi/getallprojectsandmodules
logging:
  config: config/log4j2.xml
jasypt:
  encryptor:
    password: 2d3b213c28575c095ae0029e05f40f77ee53ecd24af815bdff5479
